#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug      # change this option for non-debug runs
#SBATCH -N 32         # you'll never need more than 1 node for the serial code
#SBATCH -t 00:20:00   # adjust the amount of time as necessary
#SBATCH -J kmer19 
#SBATCH -o kmer19.%j.stdout
#SBATCH -e kmer19.%j.error

srun -N 1 -n 32 ./kmer_hash /global/project/projectdirs/mp309/cs267-spr2018/hw3-datasets/test.txt

srun -N 2 -n 32 ./kmer_hash /global/project/projectdirs/mp309/cs267-spr2018/hw3-datasets/test.txt

srun -N 4 -n 32 ./kmer_hash /global/project/projectdirs/mp309/cs267-spr2018/hw3-datasets/test.txt

srun -N 8 -n 32 ./kmer_hash /global/project/projectdirs/mp309/cs267-spr2018/hw3-datasets/test.txt



